"""empty message

Revision ID: 099539ca7da1
Revises: 265b604e6adc
Create Date: 2018-08-30 14:45:44.703824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099539ca7da1'
down_revision = '265b604e6adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('u_name', sa.String(length=16), nullable=True),
    sa.Column('_u_password', sa.String(length=256), nullable=True),
    sa.Column('u_phone', sa.String(length=16), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('u_permission', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_name'),
    sa.UniqueConstraint('u_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
