"""empty message

Revision ID: 265b604e6adc
Revises: 
Create Date: 2018-08-30 09:41:10.908419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265b604e6adc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('m_name', sa.String(length=64), nullable=True),
    sa.Column('m_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
