"""empty message

Revision ID: 1be61a3de11f
Revises: b3a68a9d2022
Create Date: 2018-08-29 15:29:15.172606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be61a3de11f'
down_revision = 'b3a68a9d2022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('m_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m_name', sa.String(length=64), nullable=True),
    sa.Column('m_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('m_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
