"""empty message

Revision ID: e30d51c485d1
Revises: 1be61a3de11f
Create Date: 2018-08-29 15:43:08.482446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30d51c485d1'
down_revision = '1be61a3de11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('b_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('b_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
